package org.hibernate;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

//import org.hibernate.annotations.Entity;

// Generated 06-Aug-2021, 2:48:07 pm by Hibernate Tools 5.4.30.Final

/**
 * AllRequiredId generated by hbm2java
 */
@Entity
@Table(name = "allRequired")
public class AllRequiredId implements java.io.Serializable {

	private String name;
	@Id
	@GeneratedValue
	private Integer id;
	private Integer fees;
	private String course;
	private String result;

	public AllRequiredId() {
	}

	public AllRequiredId(String name, Integer id, Integer fees, String course, String result) {
		this.name = name;
		this.id = id;
		this.fees = fees;
		this.course = course;
		this.result = result;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getFees() {
		return this.fees;
	}

	public void setFees(Integer fees) {
		this.fees = fees;
	}

	public String getCourse() {
		return this.course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AllRequiredId))
			return false;
		AllRequiredId castOther = (AllRequiredId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getFees() == castOther.getFees()) || (this.getFees() != null && castOther.getFees() != null
						&& this.getFees().equals(castOther.getFees())))
				&& ((this.getCourse() == castOther.getCourse()) || (this.getCourse() != null
						&& castOther.getCourse() != null && this.getCourse().equals(castOther.getCourse())))
				&& ((this.getResult() == castOther.getResult()) || (this.getResult() != null
						&& castOther.getResult() != null && this.getResult().equals(castOther.getResult())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getFees() == null ? 0 : this.getFees().hashCode());
		result = 37 * result + (getCourse() == null ? 0 : this.getCourse().hashCode());
		result = 37 * result + (getResult() == null ? 0 : this.getResult().hashCode());
		return result;
	}

}
