package org.hibernate;
// Generated 06-Aug-2021, 2:48:07 pm by Hibernate Tools 5.4.30.Final

/**
 * AllRequired generated by hbm2java
 */
public class AllRequired implements java.io.Serializable {

	private AllRequiredId id;

	public AllRequired() {
	}

	public AllRequired(AllRequiredId id) {
		this.id = id;
	}

	public AllRequiredId getId() {
		return this.id;
	}

	public void setId(AllRequiredId id) {
		this.id = id;
	}

}
